// <auto-generated/>
#pragma warning disable CS0618
using AcuCarShowClient.Api.CarDetails.Insured;
using AcuCarShowClient.Api.CarDetails.Item;
using AcuCarShowClient.Api.CarDetails.Make;
using AcuCarShowClient.Api.CarDetails.Owner;
using AcuCarShowClient.Api.CarDetails.Paged;
using AcuCarShowClient.Api.CarDetails.YearRange;
using AcuCarShowClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AcuCarShowClient.Api.CarDetails
{
    /// <summary>
    /// Builds and executes requests for operations under \api\CarDetails
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CarDetailsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The insured property</summary>
        public global::AcuCarShowClient.Api.CarDetails.Insured.InsuredRequestBuilder Insured
        {
            get => new global::AcuCarShowClient.Api.CarDetails.Insured.InsuredRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The make property</summary>
        public global::AcuCarShowClient.Api.CarDetails.Make.MakeRequestBuilder Make
        {
            get => new global::AcuCarShowClient.Api.CarDetails.Make.MakeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The owner property</summary>
        public global::AcuCarShowClient.Api.CarDetails.Owner.OwnerRequestBuilder Owner
        {
            get => new global::AcuCarShowClient.Api.CarDetails.Owner.OwnerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The paged property</summary>
        public global::AcuCarShowClient.Api.CarDetails.Paged.PagedRequestBuilder Paged
        {
            get => new global::AcuCarShowClient.Api.CarDetails.Paged.PagedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The yearRange property</summary>
        public global::AcuCarShowClient.Api.CarDetails.YearRange.YearRangeRequestBuilder YearRange
        {
            get => new global::AcuCarShowClient.Api.CarDetails.YearRange.YearRangeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the AcuCarShowClient.api.CarDetails.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarDetails.Item.WithVinItemRequestBuilder"/></returns>
        public global::AcuCarShowClient.Api.CarDetails.Item.WithVinItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("vin", position);
                return new global::AcuCarShowClient.Api.CarDetails.Item.WithVinItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarDetails.CarDetailsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CarDetailsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarDetails", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarDetails.CarDetailsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CarDetailsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarDetails", rawUrl)
        {
        }
        /// <returns>A List&lt;global::AcuCarShowClient.Models.CarDetailDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::AcuCarShowClient.Models.CarDetailDto>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::AcuCarShowClient.Models.CarDetailDto>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::AcuCarShowClient.Models.CarDetailDto>(requestInfo, global::AcuCarShowClient.Models.CarDetailDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="global::AcuCarShowClient.Models.CarDetailDto"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::AcuCarShowClient.Models.CarDetailDto?> PostAsync(global::AcuCarShowClient.Models.CarDetailDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::AcuCarShowClient.Models.CarDetailDto> PostAsync(global::AcuCarShowClient.Models.CarDetailDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::AcuCarShowClient.Models.CarDetailDto>(requestInfo, global::AcuCarShowClient.Models.CarDetailDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::AcuCarShowClient.Models.CarDetailDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::AcuCarShowClient.Models.CarDetailDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarDetails.CarDetailsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AcuCarShowClient.Api.CarDetails.CarDetailsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AcuCarShowClient.Api.CarDetails.CarDetailsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CarDetailsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CarDetailsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
