// <auto-generated/>
#pragma warning disable CS0618
using AcuCarShowClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AcuCarShowClient.Api.CarDetails.YearRange
{
    /// <summary>
    /// Builds and executes requests for operations under \api\CarDetails\year-range
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class YearRangeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarDetails.YearRange.YearRangeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public YearRangeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarDetails/year-range{?maxYear*,minYear*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarDetails.YearRange.YearRangeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public YearRangeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarDetails/year-range{?maxYear*,minYear*}", rawUrl)
        {
        }
        /// <returns>A List&lt;global::AcuCarShowClient.Models.CarDetailDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::AcuCarShowClient.Models.CarDetailDto>?> GetAsync(Action<RequestConfiguration<global::AcuCarShowClient.Api.CarDetails.YearRange.YearRangeRequestBuilder.YearRangeRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::AcuCarShowClient.Models.CarDetailDto>> GetAsync(Action<RequestConfiguration<global::AcuCarShowClient.Api.CarDetails.YearRange.YearRangeRequestBuilder.YearRangeRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::AcuCarShowClient.Models.CarDetailDto>(requestInfo, global::AcuCarShowClient.Models.CarDetailDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::AcuCarShowClient.Api.CarDetails.YearRange.YearRangeRequestBuilder.YearRangeRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::AcuCarShowClient.Api.CarDetails.YearRange.YearRangeRequestBuilder.YearRangeRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarDetails.YearRange.YearRangeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AcuCarShowClient.Api.CarDetails.YearRange.YearRangeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AcuCarShowClient.Api.CarDetails.YearRange.YearRangeRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class YearRangeRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("maxYear")]
            public int? MaxYear { get; set; }
            [QueryParameter("minYear")]
            public int? MinYear { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class YearRangeRequestBuilderGetRequestConfiguration : RequestConfiguration<global::AcuCarShowClient.Api.CarDetails.YearRange.YearRangeRequestBuilder.YearRangeRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
