// <auto-generated/>
#pragma warning disable CS0618
using AcuCarShowClient.Api.Payments.Operations.DailySummary;
using AcuCarShowClient.Api.Payments.Operations.Exceptions;
using AcuCarShowClient.Api.Payments.Operations.Export;
using AcuCarShowClient.Api.Payments.Operations.Summary;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AcuCarShowClient.Api.Payments.Operations
{
    /// <summary>
    /// Builds and executes requests for operations under \api\payments\operations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OperationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The dailySummary property</summary>
        public global::AcuCarShowClient.Api.Payments.Operations.DailySummary.DailySummaryRequestBuilder DailySummary
        {
            get => new global::AcuCarShowClient.Api.Payments.Operations.DailySummary.DailySummaryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exceptions property</summary>
        public global::AcuCarShowClient.Api.Payments.Operations.Exceptions.ExceptionsRequestBuilder Exceptions
        {
            get => new global::AcuCarShowClient.Api.Payments.Operations.Exceptions.ExceptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The export property</summary>
        public global::AcuCarShowClient.Api.Payments.Operations.Export.ExportRequestBuilder Export
        {
            get => new global::AcuCarShowClient.Api.Payments.Operations.Export.ExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The summary property</summary>
        public global::AcuCarShowClient.Api.Payments.Operations.Summary.SummaryRequestBuilder Summary
        {
            get => new global::AcuCarShowClient.Api.Payments.Operations.Summary.SummaryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.Payments.Operations.OperationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OperationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/payments/operations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.Payments.Operations.OperationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OperationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/payments/operations", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
