// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AcuCarShowClient.Api.Payments.Operations.Exceptions
{
    /// <summary>
    /// Builds and executes requests for operations under \api\payments\operations\exceptions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExceptionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.Payments.Operations.Exceptions.ExceptionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExceptionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/payments/operations/exceptions{?fromUtc*,mismatch*,missingProof*,pendingMinutesThreshold*,showId*,toUtc*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.Payments.Operations.Exceptions.ExceptionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExceptionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/payments/operations/exceptions{?fromUtc*,mismatch*,missingProof*,pendingMinutesThreshold*,showId*,toUtc*}", rawUrl)
        {
        }
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::AcuCarShowClient.Api.Payments.Operations.Exceptions.ExceptionsRequestBuilder.ExceptionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::AcuCarShowClient.Api.Payments.Operations.Exceptions.ExceptionsRequestBuilder.ExceptionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::AcuCarShowClient.Api.Payments.Operations.Exceptions.ExceptionsRequestBuilder.ExceptionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::AcuCarShowClient.Api.Payments.Operations.Exceptions.ExceptionsRequestBuilder.ExceptionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.Payments.Operations.Exceptions.ExceptionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AcuCarShowClient.Api.Payments.Operations.Exceptions.ExceptionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AcuCarShowClient.Api.Payments.Operations.Exceptions.ExceptionsRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class ExceptionsRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("fromUtc")]
            public DateTimeOffset? FromUtc { get; set; }
            [QueryParameter("mismatch")]
            public bool? Mismatch { get; set; }
            [QueryParameter("missingProof")]
            public bool? MissingProof { get; set; }
            [QueryParameter("pendingMinutesThreshold")]
            public int? PendingMinutesThreshold { get; set; }
            [QueryParameter("showId")]
            public int? ShowId { get; set; }
            [QueryParameter("toUtc")]
            public DateTimeOffset? ToUtc { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExceptionsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::AcuCarShowClient.Api.Payments.Operations.Exceptions.ExceptionsRequestBuilder.ExceptionsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
