// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CarDetailDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The authenticity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Authenticity { get; set; }
#nullable restore
#else
        public string Authenticity { get; set; }
#endif
        /// <summary>The bodyType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BodyType { get; set; }
#nullable restore
#else
        public string BodyType { get; set; }
#endif
        /// <summary>The color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>The concourScore property</summary>
        public int? ConcourScore { get; set; }
        /// <summary>The documentedHistory property</summary>
        public bool? DocumentedHistory { get; set; }
        /// <summary>The engineSize property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EngineSize { get; set; }
#nullable restore
#else
        public string EngineSize { get; set; }
#endif
        /// <summary>The estimatedShowValue property</summary>
        public double? EstimatedShowValue { get; set; }
        /// <summary>The exterior property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Exterior { get; set; }
#nullable restore
#else
        public string Exterior { get; set; }
#endif
        /// <summary>The fuelType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FuelType { get; set; }
#nullable restore
#else
        public string FuelType { get; set; }
#endif
        /// <summary>The historicalSignificance property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HistoricalSignificance { get; set; }
#nullable restore
#else
        public string HistoricalSignificance { get; set; }
#endif
        /// <summary>The horsepower property</summary>
        public int? Horsepower { get; set; }
        /// <summary>The insured property</summary>
        public bool? Insured { get; set; }
        /// <summary>The interior property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Interior { get; set; }
#nullable restore
#else
        public string Interior { get; set; }
#endif
        /// <summary>The judgeRatings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JudgeRatings { get; set; }
#nullable restore
#else
        public string JudgeRatings { get; set; }
#endif
        /// <summary>The licensePlate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LicensePlate { get; set; }
#nullable restore
#else
        public string LicensePlate { get; set; }
#endif
        /// <summary>The make property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Make { get; set; }
#nullable restore
#else
        public string Make { get; set; }
#endif
        /// <summary>The mechanicalCondition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MechanicalCondition { get; set; }
#nullable restore
#else
        public string MechanicalCondition { get; set; }
#endif
        /// <summary>The mileage property</summary>
        public int? Mileage { get; set; }
        /// <summary>The model property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>The originalEngine property</summary>
        public bool? OriginalEngine { get; set; }
        /// <summary>The originality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Originality { get; set; }
#nullable restore
#else
        public string Originality { get; set; }
#endif
        /// <summary>The originalPaint property</summary>
        public bool? OriginalPaint { get; set; }
        /// <summary>The originalTransmission property</summary>
        public bool? OriginalTransmission { get; set; }
        /// <summary>The owner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Owner { get; set; }
#nullable restore
#else
        public string Owner { get; set; }
#endif
        /// <summary>The paintCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaintCode { get; set; }
#nullable restore
#else
        public string PaintCode { get; set; }
#endif
        /// <summary>The price property</summary>
        public double? Price { get; set; }
        /// <summary>The provenance property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provenance { get; set; }
#nullable restore
#else
        public string Provenance { get; set; }
#endif
        /// <summary>The purchaseDate property</summary>
        public DateTimeOffset? PurchaseDate { get; set; }
        /// <summary>The rarity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Rarity { get; set; }
#nullable restore
#else
        public string Rarity { get; set; }
#endif
        /// <summary>The restorationStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RestorationStatus { get; set; }
#nullable restore
#else
        public string RestorationStatus { get; set; }
#endif
        /// <summary>The restorationYear property</summary>
        public int? RestorationYear { get; set; }
        /// <summary>The serviceHistory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceHistory { get; set; }
#nullable restore
#else
        public string ServiceHistory { get; set; }
#endif
        /// <summary>The showAppearances property</summary>
        public int? ShowAppearances { get; set; }
        /// <summary>The showAwards property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShowAwards { get; set; }
#nullable restore
#else
        public string ShowAwards { get; set; }
#endif
        /// <summary>The specialFeatures property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpecialFeatures { get; set; }
#nullable restore
#else
        public string SpecialFeatures { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The transmission property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Transmission { get; set; }
#nullable restore
#else
        public string Transmission { get; set; }
#endif
        /// <summary>The vin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Vin { get; set; }
#nullable restore
#else
        public string Vin { get; set; }
#endif
        /// <summary>The year property</summary>
        public int? Year { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.CarDetailDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.CarDetailDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.CarDetailDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authenticity", n => { Authenticity = n.GetStringValue(); } },
                { "bodyType", n => { BodyType = n.GetStringValue(); } },
                { "color", n => { Color = n.GetStringValue(); } },
                { "concourScore", n => { ConcourScore = n.GetIntValue(); } },
                { "documentedHistory", n => { DocumentedHistory = n.GetBoolValue(); } },
                { "engineSize", n => { EngineSize = n.GetStringValue(); } },
                { "estimatedShowValue", n => { EstimatedShowValue = n.GetDoubleValue(); } },
                { "exterior", n => { Exterior = n.GetStringValue(); } },
                { "fuelType", n => { FuelType = n.GetStringValue(); } },
                { "historicalSignificance", n => { HistoricalSignificance = n.GetStringValue(); } },
                { "horsepower", n => { Horsepower = n.GetIntValue(); } },
                { "insured", n => { Insured = n.GetBoolValue(); } },
                { "interior", n => { Interior = n.GetStringValue(); } },
                { "judgeRatings", n => { JudgeRatings = n.GetStringValue(); } },
                { "licensePlate", n => { LicensePlate = n.GetStringValue(); } },
                { "make", n => { Make = n.GetStringValue(); } },
                { "mechanicalCondition", n => { MechanicalCondition = n.GetStringValue(); } },
                { "mileage", n => { Mileage = n.GetIntValue(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "originalEngine", n => { OriginalEngine = n.GetBoolValue(); } },
                { "originalPaint", n => { OriginalPaint = n.GetBoolValue(); } },
                { "originalTransmission", n => { OriginalTransmission = n.GetBoolValue(); } },
                { "originality", n => { Originality = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetStringValue(); } },
                { "paintCode", n => { PaintCode = n.GetStringValue(); } },
                { "price", n => { Price = n.GetDoubleValue(); } },
                { "provenance", n => { Provenance = n.GetStringValue(); } },
                { "purchaseDate", n => { PurchaseDate = n.GetDateTimeOffsetValue(); } },
                { "rarity", n => { Rarity = n.GetStringValue(); } },
                { "restorationStatus", n => { RestorationStatus = n.GetStringValue(); } },
                { "restorationYear", n => { RestorationYear = n.GetIntValue(); } },
                { "serviceHistory", n => { ServiceHistory = n.GetStringValue(); } },
                { "showAppearances", n => { ShowAppearances = n.GetIntValue(); } },
                { "showAwards", n => { ShowAwards = n.GetStringValue(); } },
                { "specialFeatures", n => { SpecialFeatures = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "transmission", n => { Transmission = n.GetStringValue(); } },
                { "vin", n => { Vin = n.GetStringValue(); } },
                { "year", n => { Year = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("authenticity", Authenticity);
            writer.WriteStringValue("bodyType", BodyType);
            writer.WriteStringValue("color", Color);
            writer.WriteIntValue("concourScore", ConcourScore);
            writer.WriteBoolValue("documentedHistory", DocumentedHistory);
            writer.WriteStringValue("engineSize", EngineSize);
            writer.WriteDoubleValue("estimatedShowValue", EstimatedShowValue);
            writer.WriteStringValue("exterior", Exterior);
            writer.WriteStringValue("fuelType", FuelType);
            writer.WriteStringValue("historicalSignificance", HistoricalSignificance);
            writer.WriteIntValue("horsepower", Horsepower);
            writer.WriteBoolValue("insured", Insured);
            writer.WriteStringValue("interior", Interior);
            writer.WriteStringValue("judgeRatings", JudgeRatings);
            writer.WriteStringValue("licensePlate", LicensePlate);
            writer.WriteStringValue("make", Make);
            writer.WriteStringValue("mechanicalCondition", MechanicalCondition);
            writer.WriteIntValue("mileage", Mileage);
            writer.WriteStringValue("model", Model);
            writer.WriteBoolValue("originalEngine", OriginalEngine);
            writer.WriteStringValue("originality", Originality);
            writer.WriteBoolValue("originalPaint", OriginalPaint);
            writer.WriteBoolValue("originalTransmission", OriginalTransmission);
            writer.WriteStringValue("owner", Owner);
            writer.WriteStringValue("paintCode", PaintCode);
            writer.WriteDoubleValue("price", Price);
            writer.WriteStringValue("provenance", Provenance);
            writer.WriteDateTimeOffsetValue("purchaseDate", PurchaseDate);
            writer.WriteStringValue("rarity", Rarity);
            writer.WriteStringValue("restorationStatus", RestorationStatus);
            writer.WriteIntValue("restorationYear", RestorationYear);
            writer.WriteStringValue("serviceHistory", ServiceHistory);
            writer.WriteIntValue("showAppearances", ShowAppearances);
            writer.WriteStringValue("showAwards", ShowAwards);
            writer.WriteStringValue("specialFeatures", SpecialFeatures);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("transmission", Transmission);
            writer.WriteStringValue("vin", Vin);
            writer.WriteIntValue("year", Year);
        }
    }
}
#pragma warning restore CS0618
