// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CarShowGroupCalculationMemberDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The calculationOrder property</summary>
        public int? CalculationOrder { get; set; }
        /// <summary>The createdByUserId property</summary>
        public int? CreatedByUserId { get; set; }
        /// <summary>The groupCalculationId property</summary>
        public int? GroupCalculationId { get; set; }
        /// <summary>The groupCalculationMemberId property</summary>
        public int? GroupCalculationMemberId { get; set; }
        /// <summary>The questionCalculationGroupId property</summary>
        public int? QuestionCalculationGroupId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.CarShowGroupCalculationMemberDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.CarShowGroupCalculationMemberDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.CarShowGroupCalculationMemberDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "calculationOrder", n => { CalculationOrder = n.GetIntValue(); } },
                { "createdByUserId", n => { CreatedByUserId = n.GetIntValue(); } },
                { "groupCalculationId", n => { GroupCalculationId = n.GetIntValue(); } },
                { "groupCalculationMemberId", n => { GroupCalculationMemberId = n.GetIntValue(); } },
                { "questionCalculationGroupId", n => { QuestionCalculationGroupId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("calculationOrder", CalculationOrder);
            writer.WriteIntValue("createdByUserId", CreatedByUserId);
            writer.WriteIntValue("groupCalculationId", GroupCalculationId);
            writer.WriteIntValue("groupCalculationMemberId", GroupCalculationMemberId);
            writer.WriteIntValue("questionCalculationGroupId", QuestionCalculationGroupId);
        }
    }
}
#pragma warning restore CS0618
