// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CarShowEntryPaymentSessionResponseDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The canonicalAmount property</summary>
        public double? CanonicalAmount { get; set; }
        /// <summary>The checkoutUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CheckoutUrl { get; set; }
#nullable restore
#else
        public string CheckoutUrl { get; set; }
#endif
        /// <summary>The entryId property</summary>
        public int? EntryId { get; set; }
        /// <summary>The paymentProvider property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentProvider { get; set; }
#nullable restore
#else
        public string PaymentProvider { get; set; }
#endif
        /// <summary>The paymentProviderIntentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentProviderIntentId { get; set; }
#nullable restore
#else
        public string PaymentProviderIntentId { get; set; }
#endif
        /// <summary>The paymentProviderSessionId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentProviderSessionId { get; set; }
#nullable restore
#else
        public string PaymentProviderSessionId { get; set; }
#endif
        /// <summary>The paymentStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentStatus { get; set; }
#nullable restore
#else
        public string PaymentStatus { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.CarShowEntryPaymentSessionResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.CarShowEntryPaymentSessionResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.CarShowEntryPaymentSessionResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "canonicalAmount", n => { CanonicalAmount = n.GetDoubleValue(); } },
                { "checkoutUrl", n => { CheckoutUrl = n.GetStringValue(); } },
                { "entryId", n => { EntryId = n.GetIntValue(); } },
                { "paymentProvider", n => { PaymentProvider = n.GetStringValue(); } },
                { "paymentProviderIntentId", n => { PaymentProviderIntentId = n.GetStringValue(); } },
                { "paymentProviderSessionId", n => { PaymentProviderSessionId = n.GetStringValue(); } },
                { "paymentStatus", n => { PaymentStatus = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("canonicalAmount", CanonicalAmount);
            writer.WriteStringValue("checkoutUrl", CheckoutUrl);
            writer.WriteIntValue("entryId", EntryId);
            writer.WriteStringValue("paymentProvider", PaymentProvider);
            writer.WriteStringValue("paymentProviderIntentId", PaymentProviderIntentId);
            writer.WriteStringValue("paymentProviderSessionId", PaymentProviderSessionId);
            writer.WriteStringValue("paymentStatus", PaymentStatus);
        }
    }
}
#pragma warning restore CS0618
