// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CarShowGroupCalculationScoreDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The calculationName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CalculationName { get; set; }
#nullable restore
#else
        public string CalculationName { get; set; }
#endif
        /// <summary>The groupCalculationId property</summary>
        public int? GroupCalculationId { get; set; }
        /// <summary>The operationType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OperationType { get; set; }
#nullable restore
#else
        public string OperationType { get; set; }
#endif
        /// <summary>The questionCalculationGroupIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? QuestionCalculationGroupIds { get; set; }
#nullable restore
#else
        public List<int?> QuestionCalculationGroupIds { get; set; }
#endif
        /// <summary>The score property</summary>
        public double? Score { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.CarShowGroupCalculationScoreDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.CarShowGroupCalculationScoreDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.CarShowGroupCalculationScoreDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "calculationName", n => { CalculationName = n.GetStringValue(); } },
                { "groupCalculationId", n => { GroupCalculationId = n.GetIntValue(); } },
                { "operationType", n => { OperationType = n.GetStringValue(); } },
                { "questionCalculationGroupIds", n => { QuestionCalculationGroupIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "score", n => { Score = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("calculationName", CalculationName);
            writer.WriteIntValue("groupCalculationId", GroupCalculationId);
            writer.WriteStringValue("operationType", OperationType);
            writer.WriteCollectionOfPrimitiveValues<int?>("questionCalculationGroupIds", QuestionCalculationGroupIds);
            writer.WriteDoubleValue("score", Score);
        }
    }
}
#pragma warning restore CS0618
