// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CarShowClassDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
        public bool? Active { get; set; }
        /// <summary>The classId property</summary>
        public int? ClassId { get; set; }
        /// <summary>The className property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClassName { get; set; }
#nullable restore
#else
        public string ClassName { get; set; }
#endif
        /// <summary>The createdByUserId property</summary>
        public int? CreatedByUserId { get; set; }
        /// <summary>The customCriteria property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomCriteria { get; set; }
#nullable restore
#else
        public string CustomCriteria { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The displayOrder property</summary>
        public int? DisplayOrder { get; set; }
        /// <summary>The expectedEntries property</summary>
        public int? ExpectedEntries { get; set; }
        /// <summary>The maxYear property</summary>
        public int? MaxYear { get; set; }
        /// <summary>The minYear property</summary>
        public int? MinYear { get; set; }
        /// <summary>The optionId property</summary>
        public int? OptionId { get; set; }
        /// <summary>The showId property</summary>
        public int? ShowId { get; set; }
        /// <summary>The typeId property</summary>
        public int? TypeId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.CarShowClassDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.CarShowClassDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.CarShowClassDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "classId", n => { ClassId = n.GetIntValue(); } },
                { "className", n => { ClassName = n.GetStringValue(); } },
                { "createdByUserId", n => { CreatedByUserId = n.GetIntValue(); } },
                { "customCriteria", n => { CustomCriteria = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "displayOrder", n => { DisplayOrder = n.GetIntValue(); } },
                { "expectedEntries", n => { ExpectedEntries = n.GetIntValue(); } },
                { "maxYear", n => { MaxYear = n.GetIntValue(); } },
                { "minYear", n => { MinYear = n.GetIntValue(); } },
                { "optionId", n => { OptionId = n.GetIntValue(); } },
                { "showId", n => { ShowId = n.GetIntValue(); } },
                { "typeId", n => { TypeId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteIntValue("classId", ClassId);
            writer.WriteStringValue("className", ClassName);
            writer.WriteIntValue("createdByUserId", CreatedByUserId);
            writer.WriteStringValue("customCriteria", CustomCriteria);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("displayOrder", DisplayOrder);
            writer.WriteIntValue("expectedEntries", ExpectedEntries);
            writer.WriteIntValue("maxYear", MaxYear);
            writer.WriteIntValue("minYear", MinYear);
            writer.WriteIntValue("optionId", OptionId);
            writer.WriteIntValue("showId", ShowId);
            writer.WriteIntValue("typeId", TypeId);
        }
    }
}
#pragma warning restore CS0618
