// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CarShowFinalScoreDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The calculatedByUserId property</summary>
        public int? CalculatedByUserId { get; set; }
        /// <summary>The calculatedDate property</summary>
        public DateTimeOffset? CalculatedDate { get; set; }
        /// <summary>The calculationSummary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CalculationSummary { get; set; }
#nullable restore
#else
        public string CalculationSummary { get; set; }
#endif
        /// <summary>The entryId property</summary>
        public int? EntryId { get; set; }
        /// <summary>The finalScoreId property</summary>
        public int? FinalScoreId { get; set; }
        /// <summary>The score property</summary>
        public double? Score { get; set; }
        /// <summary>The showId property</summary>
        public int? ShowId { get; set; }
        /// <summary>The vin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Vin { get; set; }
#nullable restore
#else
        public string Vin { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.CarShowFinalScoreDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.CarShowFinalScoreDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.CarShowFinalScoreDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "calculatedByUserId", n => { CalculatedByUserId = n.GetIntValue(); } },
                { "calculatedDate", n => { CalculatedDate = n.GetDateTimeOffsetValue(); } },
                { "calculationSummary", n => { CalculationSummary = n.GetStringValue(); } },
                { "entryId", n => { EntryId = n.GetIntValue(); } },
                { "finalScoreId", n => { FinalScoreId = n.GetIntValue(); } },
                { "score", n => { Score = n.GetDoubleValue(); } },
                { "showId", n => { ShowId = n.GetIntValue(); } },
                { "vin", n => { Vin = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("calculatedByUserId", CalculatedByUserId);
            writer.WriteDateTimeOffsetValue("calculatedDate", CalculatedDate);
            writer.WriteStringValue("calculationSummary", CalculationSummary);
            writer.WriteIntValue("entryId", EntryId);
            writer.WriteIntValue("finalScoreId", FinalScoreId);
            writer.WriteDoubleValue("score", Score);
            writer.WriteIntValue("showId", ShowId);
            writer.WriteStringValue("vin", Vin);
        }
    }
}
#pragma warning restore CS0618
