// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CarShowScoreCalculationResultDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The entryId property</summary>
        public int? EntryId { get; set; }
        /// <summary>The finalScore property</summary>
        public double? FinalScore { get; set; }
        /// <summary>The groupCalculationScores property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AcuCarShowClient.Models.CarShowGroupCalculationScoreDto>? GroupCalculationScores { get; set; }
#nullable restore
#else
        public List<global::AcuCarShowClient.Models.CarShowGroupCalculationScoreDto> GroupCalculationScores { get; set; }
#endif
        /// <summary>The questionGroupScores property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupScoreDto>? QuestionGroupScores { get; set; }
#nullable restore
#else
        public List<global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupScoreDto> QuestionGroupScores { get; set; }
#endif
        /// <summary>The showId property</summary>
        public int? ShowId { get; set; }
        /// <summary>The vin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Vin { get; set; }
#nullable restore
#else
        public string Vin { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.CarShowScoreCalculationResultDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.CarShowScoreCalculationResultDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.CarShowScoreCalculationResultDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "entryId", n => { EntryId = n.GetIntValue(); } },
                { "finalScore", n => { FinalScore = n.GetDoubleValue(); } },
                { "groupCalculationScores", n => { GroupCalculationScores = n.GetCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowGroupCalculationScoreDto>(global::AcuCarShowClient.Models.CarShowGroupCalculationScoreDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "questionGroupScores", n => { QuestionGroupScores = n.GetCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupScoreDto>(global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupScoreDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "showId", n => { ShowId = n.GetIntValue(); } },
                { "vin", n => { Vin = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("entryId", EntryId);
            writer.WriteDoubleValue("finalScore", FinalScore);
            writer.WriteCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowGroupCalculationScoreDto>("groupCalculationScores", GroupCalculationScores);
            writer.WriteCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupScoreDto>("questionGroupScores", QuestionGroupScores);
            writer.WriteIntValue("showId", ShowId);
            writer.WriteStringValue("vin", Vin);
        }
    }
}
#pragma warning restore CS0618
