// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CarShowEntryDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The answers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AcuCarShowClient.Models.CarShowAnswerDto>? Answers { get; set; }
#nullable restore
#else
        public List<global::AcuCarShowClient.Models.CarShowAnswerDto> Answers { get; set; }
#endif
        /// <summary>The carDetail property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AcuCarShowClient.Models.CarDetailDto? CarDetail { get; set; }
#nullable restore
#else
        public global::AcuCarShowClient.Models.CarDetailDto CarDetail { get; set; }
#endif
        /// <summary>The category property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Category { get; set; }
#nullable restore
#else
        public string Category { get; set; }
#endif
        /// <summary>The classId property</summary>
        public int? ClassId { get; set; }
        /// <summary>The entryId property</summary>
        public int? EntryId { get; set; }
        /// <summary>The entryNumber property</summary>
        public int? EntryNumber { get; set; }
        /// <summary>The judgeScore property</summary>
        public double? JudgeScore { get; set; }
        /// <summary>The notes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The placement property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Placement { get; set; }
#nullable restore
#else
        public string Placement { get; set; }
#endif
        /// <summary>The registrationDate property</summary>
        public DateTimeOffset? RegistrationDate { get; set; }
        /// <summary>The showId property</summary>
        public int? ShowId { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The vin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Vin { get; set; }
#nullable restore
#else
        public string Vin { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.CarShowEntryDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.CarShowEntryDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.CarShowEntryDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "answers", n => { Answers = n.GetCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowAnswerDto>(global::AcuCarShowClient.Models.CarShowAnswerDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "carDetail", n => { CarDetail = n.GetObjectValue<global::AcuCarShowClient.Models.CarDetailDto>(global::AcuCarShowClient.Models.CarDetailDto.CreateFromDiscriminatorValue); } },
                { "category", n => { Category = n.GetStringValue(); } },
                { "classId", n => { ClassId = n.GetIntValue(); } },
                { "entryId", n => { EntryId = n.GetIntValue(); } },
                { "entryNumber", n => { EntryNumber = n.GetIntValue(); } },
                { "judgeScore", n => { JudgeScore = n.GetDoubleValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "placement", n => { Placement = n.GetStringValue(); } },
                { "registrationDate", n => { RegistrationDate = n.GetDateTimeOffsetValue(); } },
                { "showId", n => { ShowId = n.GetIntValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "vin", n => { Vin = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowAnswerDto>("answers", Answers);
            writer.WriteObjectValue<global::AcuCarShowClient.Models.CarDetailDto>("carDetail", CarDetail);
            writer.WriteStringValue("category", Category);
            writer.WriteIntValue("classId", ClassId);
            writer.WriteIntValue("entryId", EntryId);
            writer.WriteIntValue("entryNumber", EntryNumber);
            writer.WriteDoubleValue("judgeScore", JudgeScore);
            writer.WriteStringValue("notes", Notes);
            writer.WriteStringValue("placement", Placement);
            writer.WriteDateTimeOffsetValue("registrationDate", RegistrationDate);
            writer.WriteIntValue("showId", ShowId);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("vin", Vin);
        }
    }
}
#pragma warning restore CS0618
