// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CarShowEntryPaymentDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The entryId property</summary>
        public int? EntryId { get; set; }
        /// <summary>The paidAmount property</summary>
        public double? PaidAmount { get; set; }
        /// <summary>The paidAtUtc property</summary>
        public DateTimeOffset? PaidAtUtc { get; set; }
        /// <summary>The paidByUserId property</summary>
        public int? PaidByUserId { get; set; }
        /// <summary>The paymentProofReference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentProofReference { get; set; }
#nullable restore
#else
        public string PaymentProofReference { get; set; }
#endif
        /// <summary>The paymentProvider property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentProvider { get; set; }
#nullable restore
#else
        public string PaymentProvider { get; set; }
#endif
        /// <summary>The paymentProviderIntentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentProviderIntentId { get; set; }
#nullable restore
#else
        public string PaymentProviderIntentId { get; set; }
#endif
        /// <summary>The paymentProviderSessionId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentProviderSessionId { get; set; }
#nullable restore
#else
        public string PaymentProviderSessionId { get; set; }
#endif
        /// <summary>The paymentStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentStatus { get; set; }
#nullable restore
#else
        public string PaymentStatus { get; set; }
#endif
        /// <summary>The paymentTiming property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentTiming { get; set; }
#nullable restore
#else
        public string PaymentTiming { get; set; }
#endif
        /// <summary>The preferredPaymentMethod property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreferredPaymentMethod { get; set; }
#nullable restore
#else
        public string PreferredPaymentMethod { get; set; }
#endif
        /// <summary>The rowVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RowVersion { get; set; }
#nullable restore
#else
        public string RowVersion { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.CarShowEntryPaymentDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.CarShowEntryPaymentDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.CarShowEntryPaymentDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "entryId", n => { EntryId = n.GetIntValue(); } },
                { "paidAmount", n => { PaidAmount = n.GetDoubleValue(); } },
                { "paidAtUtc", n => { PaidAtUtc = n.GetDateTimeOffsetValue(); } },
                { "paidByUserId", n => { PaidByUserId = n.GetIntValue(); } },
                { "paymentProofReference", n => { PaymentProofReference = n.GetStringValue(); } },
                { "paymentProvider", n => { PaymentProvider = n.GetStringValue(); } },
                { "paymentProviderIntentId", n => { PaymentProviderIntentId = n.GetStringValue(); } },
                { "paymentProviderSessionId", n => { PaymentProviderSessionId = n.GetStringValue(); } },
                { "paymentStatus", n => { PaymentStatus = n.GetStringValue(); } },
                { "paymentTiming", n => { PaymentTiming = n.GetStringValue(); } },
                { "preferredPaymentMethod", n => { PreferredPaymentMethod = n.GetStringValue(); } },
                { "rowVersion", n => { RowVersion = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("entryId", EntryId);
            writer.WriteDoubleValue("paidAmount", PaidAmount);
            writer.WriteDateTimeOffsetValue("paidAtUtc", PaidAtUtc);
            writer.WriteIntValue("paidByUserId", PaidByUserId);
            writer.WriteStringValue("paymentProofReference", PaymentProofReference);
            writer.WriteStringValue("paymentProvider", PaymentProvider);
            writer.WriteStringValue("paymentProviderIntentId", PaymentProviderIntentId);
            writer.WriteStringValue("paymentProviderSessionId", PaymentProviderSessionId);
            writer.WriteStringValue("paymentStatus", PaymentStatus);
            writer.WriteStringValue("paymentTiming", PaymentTiming);
            writer.WriteStringValue("preferredPaymentMethod", PreferredPaymentMethod);
            writer.WriteStringValue("rowVersion", RowVersion);
        }
    }
}
#pragma warning restore CS0618
