// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CarShowDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
        public bool? Active { get; set; }
        /// <summary>The category property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Category { get; set; }
#nullable restore
#else
        public string Category { get; set; }
#endif
        /// <summary>The classes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AcuCarShowClient.Models.CarShowClassDto>? Classes { get; set; }
#nullable restore
#else
        public List<global::AcuCarShowClient.Models.CarShowClassDto> Classes { get; set; }
#endif
        /// <summary>The createdBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The createdDate property</summary>
        public DateTimeOffset? CreatedDate { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The endDate property</summary>
        public DateTimeOffset? EndDate { get; set; }
        /// <summary>The entries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AcuCarShowClient.Models.CarShowEntryDto>? Entries { get; set; }
#nullable restore
#else
        public List<global::AcuCarShowClient.Models.CarShowEntryDto> Entries { get; set; }
#endif
        /// <summary>The eventDate property</summary>
        public DateTimeOffset? EventDate { get; set; }
        /// <summary>The judgeType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JudgeType { get; set; }
#nullable restore
#else
        public string JudgeType { get; set; }
#endif
        /// <summary>The location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Location { get; set; }
#nullable restore
#else
        public string Location { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The scoringFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScoringFormat { get; set; }
#nullable restore
#else
        public string ScoringFormat { get; set; }
#endif
        /// <summary>The scoringQuestions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AcuCarShowClient.Models.CarShowScoringQuestionDto>? ScoringQuestions { get; set; }
#nullable restore
#else
        public List<global::AcuCarShowClient.Models.CarShowScoringQuestionDto> ScoringQuestions { get; set; }
#endif
        /// <summary>The showId property</summary>
        public int? ShowId { get; set; }
        /// <summary>The totalParticipants property</summary>
        public int? TotalParticipants { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.CarShowDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.CarShowDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.CarShowDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "category", n => { Category = n.GetStringValue(); } },
                { "classes", n => { Classes = n.GetCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowClassDto>(global::AcuCarShowClient.Models.CarShowClassDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "createdDate", n => { CreatedDate = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "endDate", n => { EndDate = n.GetDateTimeOffsetValue(); } },
                { "entries", n => { Entries = n.GetCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowEntryDto>(global::AcuCarShowClient.Models.CarShowEntryDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "eventDate", n => { EventDate = n.GetDateTimeOffsetValue(); } },
                { "judgeType", n => { JudgeType = n.GetStringValue(); } },
                { "location", n => { Location = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "scoringFormat", n => { ScoringFormat = n.GetStringValue(); } },
                { "scoringQuestions", n => { ScoringQuestions = n.GetCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowScoringQuestionDto>(global::AcuCarShowClient.Models.CarShowScoringQuestionDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "showId", n => { ShowId = n.GetIntValue(); } },
                { "totalParticipants", n => { TotalParticipants = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteStringValue("category", Category);
            writer.WriteCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowClassDto>("classes", Classes);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteDateTimeOffsetValue("createdDate", CreatedDate);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("endDate", EndDate);
            writer.WriteCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowEntryDto>("entries", Entries);
            writer.WriteDateTimeOffsetValue("eventDate", EventDate);
            writer.WriteStringValue("judgeType", JudgeType);
            writer.WriteStringValue("location", Location);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("scoringFormat", ScoringFormat);
            writer.WriteCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowScoringQuestionDto>("scoringQuestions", ScoringQuestions);
            writer.WriteIntValue("showId", ShowId);
            writer.WriteIntValue("totalParticipants", TotalParticipants);
        }
    }
}
#pragma warning restore CS0618
