// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CarShowQuestionCalculationGroupDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
        public bool? Active { get; set; }
        /// <summary>The createdByUserId property</summary>
        public int? CreatedByUserId { get; set; }
        /// <summary>The createdDate property</summary>
        public DateTimeOffset? CreatedDate { get; set; }
        /// <summary>The groupName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupName { get; set; }
#nullable restore
#else
        public string GroupName { get; set; }
#endif
        /// <summary>The operationType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OperationType { get; set; }
#nullable restore
#else
        public string OperationType { get; set; }
#endif
        /// <summary>The questionCalculationGroupId property</summary>
        public int? QuestionCalculationGroupId { get; set; }
        /// <summary>The questions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupQuestionDto>? Questions { get; set; }
#nullable restore
#else
        public List<global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupQuestionDto> Questions { get; set; }
#endif
        /// <summary>The showId property</summary>
        public int? ShowId { get; set; }
        /// <summary>The sortOrder property</summary>
        public int? SortOrder { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "createdByUserId", n => { CreatedByUserId = n.GetIntValue(); } },
                { "createdDate", n => { CreatedDate = n.GetDateTimeOffsetValue(); } },
                { "groupName", n => { GroupName = n.GetStringValue(); } },
                { "operationType", n => { OperationType = n.GetStringValue(); } },
                { "questionCalculationGroupId", n => { QuestionCalculationGroupId = n.GetIntValue(); } },
                { "questions", n => { Questions = n.GetCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupQuestionDto>(global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupQuestionDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "showId", n => { ShowId = n.GetIntValue(); } },
                { "sortOrder", n => { SortOrder = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteIntValue("createdByUserId", CreatedByUserId);
            writer.WriteDateTimeOffsetValue("createdDate", CreatedDate);
            writer.WriteStringValue("groupName", GroupName);
            writer.WriteStringValue("operationType", OperationType);
            writer.WriteIntValue("questionCalculationGroupId", QuestionCalculationGroupId);
            writer.WriteCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupQuestionDto>("questions", Questions);
            writer.WriteIntValue("showId", ShowId);
            writer.WriteIntValue("sortOrder", SortOrder);
        }
    }
}
#pragma warning restore CS0618
