// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CarShowClassOptionDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
        public bool? Active { get; set; }
        /// <summary>The category property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Category { get; set; }
#nullable restore
#else
        public string Category { get; set; }
#endif
        /// <summary>The createdByUserId property</summary>
        public int? CreatedByUserId { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The endYear property</summary>
        public int? EndYear { get; set; }
        /// <summary>The optionId property</summary>
        public int? OptionId { get; set; }
        /// <summary>The optionValue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OptionValue { get; set; }
#nullable restore
#else
        public string OptionValue { get; set; }
#endif
        /// <summary>The startYear property</summary>
        public int? StartYear { get; set; }
        /// <summary>The typeId property</summary>
        public int? TypeId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.CarShowClassOptionDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.CarShowClassOptionDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.CarShowClassOptionDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "category", n => { Category = n.GetStringValue(); } },
                { "createdByUserId", n => { CreatedByUserId = n.GetIntValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "endYear", n => { EndYear = n.GetIntValue(); } },
                { "optionId", n => { OptionId = n.GetIntValue(); } },
                { "optionValue", n => { OptionValue = n.GetStringValue(); } },
                { "startYear", n => { StartYear = n.GetIntValue(); } },
                { "typeId", n => { TypeId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteStringValue("category", Category);
            writer.WriteIntValue("createdByUserId", CreatedByUserId);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("endYear", EndYear);
            writer.WriteIntValue("optionId", OptionId);
            writer.WriteStringValue("optionValue", OptionValue);
            writer.WriteIntValue("startYear", StartYear);
            writer.WriteIntValue("typeId", TypeId);
        }
    }
}
#pragma warning restore CS0618
