// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CarShowScoringQuestionDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
        public bool? Active { get; set; }
        /// <summary>The answers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AcuCarShowClient.Models.CarShowAnswerDto>? Answers { get; set; }
#nullable restore
#else
        public List<global::AcuCarShowClient.Models.CarShowAnswerDto> Answers { get; set; }
#endif
        /// <summary>The answerType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnswerType { get; set; }
#nullable restore
#else
        public string AnswerType { get; set; }
#endif
        /// <summary>The calculationGroups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupQuestionDto>? CalculationGroups { get; set; }
#nullable restore
#else
        public List<global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupQuestionDto> CalculationGroups { get; set; }
#endif
        /// <summary>The category property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Category { get; set; }
#nullable restore
#else
        public string Category { get; set; }
#endif
        /// <summary>The createdByUserId property</summary>
        public int? CreatedByUserId { get; set; }
        /// <summary>The createdDate property</summary>
        public DateTimeOffset? CreatedDate { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The judgeNotes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JudgeNotes { get; set; }
#nullable restore
#else
        public string JudgeNotes { get; set; }
#endif
        /// <summary>The maxScore property</summary>
        public int? MaxScore { get; set; }
        /// <summary>The minScore property</summary>
        public int? MinScore { get; set; }
        /// <summary>The questionId property</summary>
        public int? QuestionId { get; set; }
        /// <summary>The questionText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QuestionText { get; set; }
#nullable restore
#else
        public string QuestionText { get; set; }
#endif
        /// <summary>The required property</summary>
        public bool? Required { get; set; }
        /// <summary>The showId property</summary>
        public int? ShowId { get; set; }
        /// <summary>The sortOrder property</summary>
        public int? SortOrder { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.CarShowScoringQuestionDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.CarShowScoringQuestionDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.CarShowScoringQuestionDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "answerType", n => { AnswerType = n.GetStringValue(); } },
                { "answers", n => { Answers = n.GetCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowAnswerDto>(global::AcuCarShowClient.Models.CarShowAnswerDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "calculationGroups", n => { CalculationGroups = n.GetCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupQuestionDto>(global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupQuestionDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "category", n => { Category = n.GetStringValue(); } },
                { "createdByUserId", n => { CreatedByUserId = n.GetIntValue(); } },
                { "createdDate", n => { CreatedDate = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "judgeNotes", n => { JudgeNotes = n.GetStringValue(); } },
                { "maxScore", n => { MaxScore = n.GetIntValue(); } },
                { "minScore", n => { MinScore = n.GetIntValue(); } },
                { "questionId", n => { QuestionId = n.GetIntValue(); } },
                { "questionText", n => { QuestionText = n.GetStringValue(); } },
                { "required", n => { Required = n.GetBoolValue(); } },
                { "showId", n => { ShowId = n.GetIntValue(); } },
                { "sortOrder", n => { SortOrder = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowAnswerDto>("answers", Answers);
            writer.WriteStringValue("answerType", AnswerType);
            writer.WriteCollectionOfObjectValues<global::AcuCarShowClient.Models.CarShowQuestionCalculationGroupQuestionDto>("calculationGroups", CalculationGroups);
            writer.WriteStringValue("category", Category);
            writer.WriteIntValue("createdByUserId", CreatedByUserId);
            writer.WriteDateTimeOffsetValue("createdDate", CreatedDate);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("judgeNotes", JudgeNotes);
            writer.WriteIntValue("maxScore", MaxScore);
            writer.WriteIntValue("minScore", MinScore);
            writer.WriteIntValue("questionId", QuestionId);
            writer.WriteStringValue("questionText", QuestionText);
            writer.WriteBoolValue("required", Required);
            writer.WriteIntValue("showId", ShowId);
            writer.WriteIntValue("sortOrder", SortOrder);
        }
    }
}
#pragma warning restore CS0618
