// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaymentMethodProviderBreakdownDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The collectedAmount property</summary>
        public double? CollectedAmount { get; set; }
        /// <summary>The count property</summary>
        public int? Count { get; set; }
        /// <summary>The paymentProvider property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentProvider { get; set; }
#nullable restore
#else
        public string PaymentProvider { get; set; }
#endif
        /// <summary>The preferredPaymentMethod property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreferredPaymentMethod { get; set; }
#nullable restore
#else
        public string PreferredPaymentMethod { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.PaymentMethodProviderBreakdownDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.PaymentMethodProviderBreakdownDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.PaymentMethodProviderBreakdownDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "collectedAmount", n => { CollectedAmount = n.GetDoubleValue(); } },
                { "count", n => { Count = n.GetIntValue(); } },
                { "paymentProvider", n => { PaymentProvider = n.GetStringValue(); } },
                { "preferredPaymentMethod", n => { PreferredPaymentMethod = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("collectedAmount", CollectedAmount);
            writer.WriteIntValue("count", Count);
            writer.WriteStringValue("paymentProvider", PaymentProvider);
            writer.WriteStringValue("preferredPaymentMethod", PreferredPaymentMethod);
        }
    }
}
#pragma warning restore CS0618
