// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaymentWebhookProcessResultDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The duplicate property</summary>
        public bool? Duplicate { get; set; }
        /// <summary>The entryId property</summary>
        public int? EntryId { get; set; }
        /// <summary>The outcome property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Outcome { get; set; }
#nullable restore
#else
        public string Outcome { get; set; }
#endif
        /// <summary>The paymentStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentStatus { get; set; }
#nullable restore
#else
        public string PaymentStatus { get; set; }
#endif
        /// <summary>The processed property</summary>
        public bool? Processed { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.PaymentWebhookProcessResultDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.PaymentWebhookProcessResultDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.PaymentWebhookProcessResultDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "duplicate", n => { Duplicate = n.GetBoolValue(); } },
                { "entryId", n => { EntryId = n.GetIntValue(); } },
                { "outcome", n => { Outcome = n.GetStringValue(); } },
                { "paymentStatus", n => { PaymentStatus = n.GetStringValue(); } },
                { "processed", n => { Processed = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("duplicate", Duplicate);
            writer.WriteIntValue("entryId", EntryId);
            writer.WriteStringValue("outcome", Outcome);
            writer.WriteStringValue("paymentStatus", PaymentStatus);
            writer.WriteBoolValue("processed", Processed);
        }
    }
}
#pragma warning restore CS0618
