// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaymentOperationsSummaryDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The breakdown property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AcuCarShowClient.Models.PaymentMethodProviderBreakdownDto>? Breakdown { get; set; }
#nullable restore
#else
        public List<global::AcuCarShowClient.Models.PaymentMethodProviderBreakdownDto> Breakdown { get; set; }
#endif
        /// <summary>The collectedAmount property</summary>
        public double? CollectedAmount { get; set; }
        /// <summary>The expectedCollected property</summary>
        public double? ExpectedCollected { get; set; }
        /// <summary>The manualCount property</summary>
        public int? ManualCount { get; set; }
        /// <summary>The paidCount property</summary>
        public int? PaidCount { get; set; }
        /// <summary>The pendingCount property</summary>
        public int? PendingCount { get; set; }
        /// <summary>The totalCount property</summary>
        public int? TotalCount { get; set; }
        /// <summary>The variance property</summary>
        public double? Variance { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.PaymentOperationsSummaryDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.PaymentOperationsSummaryDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.PaymentOperationsSummaryDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "breakdown", n => { Breakdown = n.GetCollectionOfObjectValues<global::AcuCarShowClient.Models.PaymentMethodProviderBreakdownDto>(global::AcuCarShowClient.Models.PaymentMethodProviderBreakdownDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "collectedAmount", n => { CollectedAmount = n.GetDoubleValue(); } },
                { "expectedCollected", n => { ExpectedCollected = n.GetDoubleValue(); } },
                { "manualCount", n => { ManualCount = n.GetIntValue(); } },
                { "paidCount", n => { PaidCount = n.GetIntValue(); } },
                { "pendingCount", n => { PendingCount = n.GetIntValue(); } },
                { "totalCount", n => { TotalCount = n.GetIntValue(); } },
                { "variance", n => { Variance = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::AcuCarShowClient.Models.PaymentMethodProviderBreakdownDto>("breakdown", Breakdown);
            writer.WriteDoubleValue("collectedAmount", CollectedAmount);
            writer.WriteDoubleValue("expectedCollected", ExpectedCollected);
            writer.WriteIntValue("manualCount", ManualCount);
            writer.WriteIntValue("paidCount", PaidCount);
            writer.WriteIntValue("pendingCount", PendingCount);
            writer.WriteIntValue("totalCount", TotalCount);
            writer.WriteDoubleValue("variance", Variance);
        }
    }
}
#pragma warning restore CS0618
