// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UserAccessRole
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "None")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "Admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "Participant")]
        #pragma warning disable CS1591
        Participant,
        #pragma warning restore CS1591
        [EnumMember(Value = "Judge")]
        #pragma warning disable CS1591
        Judge,
        #pragma warning restore CS1591
        [EnumMember(Value = "Manager")]
        #pragma warning disable CS1591
        Manager,
        #pragma warning restore CS1591
    }
}
