// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AcuCarShowClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserApplicationAccessDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accessLevel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessLevel { get; set; }
#nullable restore
#else
        public string AccessLevel { get; set; }
#endif
        /// <summary>The accessRoles property</summary>
        public global::AcuCarShowClient.Models.UserAccessRole? AccessRoles { get; set; }
        /// <summary>The applicationId property</summary>
        public int? ApplicationId { get; set; }
        /// <summary>The canManage property</summary>
        public bool? CanManage { get; set; }
        /// <summary>The canRead property</summary>
        public bool? CanRead { get; set; }
        /// <summary>The canWrite property</summary>
        public bool? CanWrite { get; set; }
        /// <summary>The grantedDate property</summary>
        public DateTimeOffset? GrantedDate { get; set; }
        /// <summary>The userApplicationAccessId property</summary>
        public int? UserApplicationAccessId { get; set; }
        /// <summary>The userId property</summary>
        public int? UserId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Models.UserApplicationAccessDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AcuCarShowClient.Models.UserApplicationAccessDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AcuCarShowClient.Models.UserApplicationAccessDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accessLevel", n => { AccessLevel = n.GetStringValue(); } },
                { "accessRoles", n => { AccessRoles = n.GetEnumValue<global::AcuCarShowClient.Models.UserAccessRole>(); } },
                { "applicationId", n => { ApplicationId = n.GetIntValue(); } },
                { "canManage", n => { CanManage = n.GetBoolValue(); } },
                { "canRead", n => { CanRead = n.GetBoolValue(); } },
                { "canWrite", n => { CanWrite = n.GetBoolValue(); } },
                { "grantedDate", n => { GrantedDate = n.GetDateTimeOffsetValue(); } },
                { "userApplicationAccessId", n => { UserApplicationAccessId = n.GetIntValue(); } },
                { "userId", n => { UserId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accessLevel", AccessLevel);
            writer.WriteEnumValue<global::AcuCarShowClient.Models.UserAccessRole>("accessRoles", AccessRoles);
            writer.WriteIntValue("applicationId", ApplicationId);
            writer.WriteBoolValue("canManage", CanManage);
            writer.WriteBoolValue("canRead", CanRead);
            writer.WriteBoolValue("canWrite", CanWrite);
            writer.WriteDateTimeOffsetValue("grantedDate", GrantedDate);
            writer.WriteIntValue("userApplicationAccessId", UserApplicationAccessId);
            writer.WriteIntValue("userId", UserId);
        }
    }
}
#pragma warning restore CS0618
