// <auto-generated/>
#pragma warning disable CS0618
using AcuCarShowClient.Api.CarShowFinalScores.Show.Item.Entry.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AcuCarShowClient.Api.CarShowFinalScores.Show.Item.Entry
{
    /// <summary>
    /// Builds and executes requests for operations under \api\CarShowFinalScores\show\{showId}\entry
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EntryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the AcuCarShowClient.api.CarShowFinalScores.show.item.entry.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarShowFinalScores.Show.Item.Entry.Item.WithEntryItemRequestBuilder"/></returns>
        public global::AcuCarShowClient.Api.CarShowFinalScores.Show.Item.Entry.Item.WithEntryItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("entryId", position);
                return new global::AcuCarShowClient.Api.CarShowFinalScores.Show.Item.Entry.Item.WithEntryItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the AcuCarShowClient.api.CarShowFinalScores.show.item.entry.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarShowFinalScores.Show.Item.Entry.Item.WithEntryItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::AcuCarShowClient.Api.CarShowFinalScores.Show.Item.Entry.Item.WithEntryItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("entryId", position);
                return new global::AcuCarShowClient.Api.CarShowFinalScores.Show.Item.Entry.Item.WithEntryItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShowFinalScores.Show.Item.Entry.EntryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShowFinalScores/show/{showId}/entry", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShowFinalScores.Show.Item.Entry.EntryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShowFinalScores/show/{showId}/entry", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
