// <auto-generated/>
#pragma warning disable CS0618
using AcuCarShowClient.Api.CarShowClasses.TypeNamespace.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AcuCarShowClient.Api.CarShowClasses.TypeNamespace
{
    /// <summary>
    /// Builds and executes requests for operations under \api\CarShowClasses\type
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TypeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the AcuCarShowClient.api.CarShowClasses.type.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarShowClasses.TypeNamespace.Item.WithTypeItemRequestBuilder"/></returns>
        public global::AcuCarShowClient.Api.CarShowClasses.TypeNamespace.Item.WithTypeItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("typeId", position);
                return new global::AcuCarShowClient.Api.CarShowClasses.TypeNamespace.Item.WithTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the AcuCarShowClient.api.CarShowClasses.type.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarShowClasses.TypeNamespace.Item.WithTypeItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::AcuCarShowClient.Api.CarShowClasses.TypeNamespace.Item.WithTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("typeId", position);
                return new global::AcuCarShowClient.Api.CarShowClasses.TypeNamespace.Item.WithTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShowClasses.TypeNamespace.TypeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TypeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShowClasses/type", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShowClasses.TypeNamespace.TypeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TypeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShowClasses/type", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
