// <auto-generated/>
#pragma warning disable CS0618
using AcuCarShowClient.Api.CarShowGroupCalculationMembers.QuestionGroup.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AcuCarShowClient.Api.CarShowGroupCalculationMembers.QuestionGroup
{
    /// <summary>
    /// Builds and executes requests for operations under \api\CarShowGroupCalculationMembers\question-group
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QuestionGroupRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the AcuCarShowClient.api.CarShowGroupCalculationMembers.questionGroup.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarShowGroupCalculationMembers.QuestionGroup.Item.WithQuestionCalculationGroupItemRequestBuilder"/></returns>
        public global::AcuCarShowClient.Api.CarShowGroupCalculationMembers.QuestionGroup.Item.WithQuestionCalculationGroupItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("questionCalculationGroupId", position);
                return new global::AcuCarShowClient.Api.CarShowGroupCalculationMembers.QuestionGroup.Item.WithQuestionCalculationGroupItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the AcuCarShowClient.api.CarShowGroupCalculationMembers.questionGroup.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarShowGroupCalculationMembers.QuestionGroup.Item.WithQuestionCalculationGroupItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::AcuCarShowClient.Api.CarShowGroupCalculationMembers.QuestionGroup.Item.WithQuestionCalculationGroupItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("questionCalculationGroupId", position);
                return new global::AcuCarShowClient.Api.CarShowGroupCalculationMembers.QuestionGroup.Item.WithQuestionCalculationGroupItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShowGroupCalculationMembers.QuestionGroup.QuestionGroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QuestionGroupRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShowGroupCalculationMembers/question-group", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShowGroupCalculationMembers.QuestionGroup.QuestionGroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QuestionGroupRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShowGroupCalculationMembers/question-group", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
