// <auto-generated/>
#pragma warning disable CS0618
using AcuCarShowClient.Api.CarShows.Category.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AcuCarShowClient.Api.CarShows.Category
{
    /// <summary>
    /// Builds and executes requests for operations under \api\CarShows\category
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CategoryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the AcuCarShowClient.api.CarShows.category.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarShows.Category.Item.WithCategoryItemRequestBuilder"/></returns>
        public global::AcuCarShowClient.Api.CarShows.Category.Item.WithCategoryItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("category", position);
                return new global::AcuCarShowClient.Api.CarShows.Category.Item.WithCategoryItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShows.Category.CategoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CategoryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShows/category", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShows.Category.CategoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CategoryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShows/category", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
