// <auto-generated/>
#pragma warning disable CS0618
using AcuCarShowClient.Api.CarShowClassTypes.Active;
using AcuCarShowClient.Api.CarShowClassTypes.AllowMultiple;
using AcuCarShowClient.Api.CarShowClassTypes.ClassificationMethod;
using AcuCarShowClient.Api.CarShowClassTypes.Item;
using AcuCarShowClient.Api.CarShowClassTypes.Paged;
using AcuCarShowClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AcuCarShowClient.Api.CarShowClassTypes
{
    /// <summary>
    /// Builds and executes requests for operations under \api\CarShowClassTypes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CarShowClassTypesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The active property</summary>
        public global::AcuCarShowClient.Api.CarShowClassTypes.Active.ActiveRequestBuilder Active
        {
            get => new global::AcuCarShowClient.Api.CarShowClassTypes.Active.ActiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The allowMultiple property</summary>
        public global::AcuCarShowClient.Api.CarShowClassTypes.AllowMultiple.AllowMultipleRequestBuilder AllowMultiple
        {
            get => new global::AcuCarShowClient.Api.CarShowClassTypes.AllowMultiple.AllowMultipleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The classificationMethod property</summary>
        public global::AcuCarShowClient.Api.CarShowClassTypes.ClassificationMethod.ClassificationMethodRequestBuilder ClassificationMethod
        {
            get => new global::AcuCarShowClient.Api.CarShowClassTypes.ClassificationMethod.ClassificationMethodRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The paged property</summary>
        public global::AcuCarShowClient.Api.CarShowClassTypes.Paged.PagedRequestBuilder Paged
        {
            get => new global::AcuCarShowClient.Api.CarShowClassTypes.Paged.PagedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the AcuCarShowClient.api.CarShowClassTypes.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarShowClassTypes.Item.CarShowClassTypesItemRequestBuilder"/></returns>
        public global::AcuCarShowClient.Api.CarShowClassTypes.Item.CarShowClassTypesItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::AcuCarShowClient.Api.CarShowClassTypes.Item.CarShowClassTypesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the AcuCarShowClient.api.CarShowClassTypes.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarShowClassTypes.Item.CarShowClassTypesItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::AcuCarShowClient.Api.CarShowClassTypes.Item.CarShowClassTypesItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::AcuCarShowClient.Api.CarShowClassTypes.Item.CarShowClassTypesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShowClassTypes.CarShowClassTypesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CarShowClassTypesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShowClassTypes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShowClassTypes.CarShowClassTypesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CarShowClassTypesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShowClassTypes", rawUrl)
        {
        }
        /// <returns>A List&lt;global::AcuCarShowClient.Models.CarShowClassTypeDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::AcuCarShowClient.Models.CarShowClassTypeDto>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::AcuCarShowClient.Models.CarShowClassTypeDto>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::AcuCarShowClient.Models.CarShowClassTypeDto>(requestInfo, global::AcuCarShowClient.Models.CarShowClassTypeDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="global::AcuCarShowClient.Models.CarShowClassTypeDto"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::AcuCarShowClient.Models.CarShowClassTypeDto?> PostAsync(global::AcuCarShowClient.Models.CarShowClassTypeDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::AcuCarShowClient.Models.CarShowClassTypeDto> PostAsync(global::AcuCarShowClient.Models.CarShowClassTypeDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::AcuCarShowClient.Models.CarShowClassTypeDto>(requestInfo, global::AcuCarShowClient.Models.CarShowClassTypeDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::AcuCarShowClient.Models.CarShowClassTypeDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::AcuCarShowClient.Models.CarShowClassTypeDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarShowClassTypes.CarShowClassTypesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AcuCarShowClient.Api.CarShowClassTypes.CarShowClassTypesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AcuCarShowClient.Api.CarShowClassTypes.CarShowClassTypesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CarShowClassTypesRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CarShowClassTypesRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
