// <auto-generated/>
#pragma warning disable CS0618
using AcuCarShowClient.Api.CarShowScoreCalculations.Show;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AcuCarShowClient.Api.CarShowScoreCalculations
{
    /// <summary>
    /// Builds and executes requests for operations under \api\CarShowScoreCalculations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CarShowScoreCalculationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The show property</summary>
        public global::AcuCarShowClient.Api.CarShowScoreCalculations.Show.ShowRequestBuilder Show
        {
            get => new global::AcuCarShowClient.Api.CarShowScoreCalculations.Show.ShowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShowScoreCalculations.CarShowScoreCalculationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CarShowScoreCalculationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShowScoreCalculations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShowScoreCalculations.CarShowScoreCalculationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CarShowScoreCalculationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShowScoreCalculations", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
