// <auto-generated/>
#pragma warning disable CS0618
using AcuCarShowClient.Api.CarShowClassTypes.AllowMultiple.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AcuCarShowClient.Api.CarShowClassTypes.AllowMultiple
{
    /// <summary>
    /// Builds and executes requests for operations under \api\CarShowClassTypes\allow-multiple
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AllowMultipleRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the AcuCarShowClient.api.CarShowClassTypes.allowMultiple.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarShowClassTypes.AllowMultiple.Item.WithAllowMultipleItemRequestBuilder"/></returns>
        public global::AcuCarShowClient.Api.CarShowClassTypes.AllowMultiple.Item.WithAllowMultipleItemRequestBuilder this[bool position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("allowMultiple", position);
                return new global::AcuCarShowClient.Api.CarShowClassTypes.AllowMultiple.Item.WithAllowMultipleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the AcuCarShowClient.api.CarShowClassTypes.allowMultiple.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarShowClassTypes.AllowMultiple.Item.WithAllowMultipleItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::AcuCarShowClient.Api.CarShowClassTypes.AllowMultiple.Item.WithAllowMultipleItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("allowMultiple", position);
                return new global::AcuCarShowClient.Api.CarShowClassTypes.AllowMultiple.Item.WithAllowMultipleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShowClassTypes.AllowMultiple.AllowMultipleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AllowMultipleRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShowClassTypes/allow-multiple", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShowClassTypes.AllowMultiple.AllowMultipleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AllowMultipleRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShowClassTypes/allow-multiple", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
