// <auto-generated/>
#pragma warning disable CS0618
using AcuCarShowClient.Api.CarDetails.Make.Item.Model;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AcuCarShowClient.Api.CarDetails.Make.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\CarDetails\make\{make}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithMakeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The model property</summary>
        public global::AcuCarShowClient.Api.CarDetails.Make.Item.Model.ModelRequestBuilder Model
        {
            get => new global::AcuCarShowClient.Api.CarDetails.Make.Item.Model.ModelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarDetails.Make.Item.WithMakeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMakeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarDetails/make/{make}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarDetails.Make.Item.WithMakeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMakeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarDetails/make/{make}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
