// <auto-generated/>
#pragma warning disable CS0618
using AcuCarShowClient.Api.CarShowClassTypes.ClassificationMethod.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AcuCarShowClient.Api.CarShowClassTypes.ClassificationMethod
{
    /// <summary>
    /// Builds and executes requests for operations under \api\CarShowClassTypes\classification-method
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClassificationMethodRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the AcuCarShowClient.api.CarShowClassTypes.classificationMethod.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarShowClassTypes.ClassificationMethod.Item.WithClassificationMethodItemRequestBuilder"/></returns>
        public global::AcuCarShowClient.Api.CarShowClassTypes.ClassificationMethod.Item.WithClassificationMethodItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("classificationMethod", position);
                return new global::AcuCarShowClient.Api.CarShowClassTypes.ClassificationMethod.Item.WithClassificationMethodItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShowClassTypes.ClassificationMethod.ClassificationMethodRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClassificationMethodRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShowClassTypes/classification-method", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShowClassTypes.ClassificationMethod.ClassificationMethodRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClassificationMethodRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShowClassTypes/classification-method", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
