// <auto-generated/>
#pragma warning disable CS0618
using AcuCarShowClient.Api.CarShowEntries.Vin.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AcuCarShowClient.Api.CarShowEntries.Vin
{
    /// <summary>
    /// Builds and executes requests for operations under \api\CarShowEntries\vin
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VinRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the AcuCarShowClient.api.CarShowEntries.vin.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarShowEntries.Vin.Item.WithVinItemRequestBuilder"/></returns>
        public global::AcuCarShowClient.Api.CarShowEntries.Vin.Item.WithVinItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("vin", position);
                return new global::AcuCarShowClient.Api.CarShowEntries.Vin.Item.WithVinItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShowEntries.Vin.VinRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VinRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShowEntries/vin", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarShowEntries.Vin.VinRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VinRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarShowEntries/vin", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
