// <auto-generated/>
#pragma warning disable CS0618
using AcuCarShowClient.Api.CarDetails;
using AcuCarShowClient.Api.CarShowAnswers;
using AcuCarShowClient.Api.CarShowClassOptions;
using AcuCarShowClient.Api.CarShowClassTypes;
using AcuCarShowClient.Api.CarShowClasses;
using AcuCarShowClient.Api.CarShowEntries;
using AcuCarShowClient.Api.CarShowScoringQuestions;
using AcuCarShowClient.Api.CarShows;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AcuCarShowClient.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The CarDetails property</summary>
        public global::AcuCarShowClient.Api.CarDetails.CarDetailsRequestBuilder CarDetails
        {
            get => new global::AcuCarShowClient.Api.CarDetails.CarDetailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowAnswers property</summary>
        public global::AcuCarShowClient.Api.CarShowAnswers.CarShowAnswersRequestBuilder CarShowAnswers
        {
            get => new global::AcuCarShowClient.Api.CarShowAnswers.CarShowAnswersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowClasses property</summary>
        public global::AcuCarShowClient.Api.CarShowClasses.CarShowClassesRequestBuilder CarShowClasses
        {
            get => new global::AcuCarShowClient.Api.CarShowClasses.CarShowClassesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowClassOptions property</summary>
        public global::AcuCarShowClient.Api.CarShowClassOptions.CarShowClassOptionsRequestBuilder CarShowClassOptions
        {
            get => new global::AcuCarShowClient.Api.CarShowClassOptions.CarShowClassOptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowClassTypes property</summary>
        public global::AcuCarShowClient.Api.CarShowClassTypes.CarShowClassTypesRequestBuilder CarShowClassTypes
        {
            get => new global::AcuCarShowClient.Api.CarShowClassTypes.CarShowClassTypesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowEntries property</summary>
        public global::AcuCarShowClient.Api.CarShowEntries.CarShowEntriesRequestBuilder CarShowEntries
        {
            get => new global::AcuCarShowClient.Api.CarShowEntries.CarShowEntriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShows property</summary>
        public global::AcuCarShowClient.Api.CarShows.CarShowsRequestBuilder CarShows
        {
            get => new global::AcuCarShowClient.Api.CarShows.CarShowsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowScoringQuestions property</summary>
        public global::AcuCarShowClient.Api.CarShowScoringQuestions.CarShowScoringQuestionsRequestBuilder CarShowScoringQuestions
        {
            get => new global::AcuCarShowClient.Api.CarShowScoringQuestions.CarShowScoringQuestionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
