// <auto-generated/>
#pragma warning disable CS0618
using AcuCarShowClient.Api.AppUsers;
using AcuCarShowClient.Api.Applications;
using AcuCarShowClient.Api.CarDetails;
using AcuCarShowClient.Api.CarShowAnswers;
using AcuCarShowClient.Api.CarShowClassOptions;
using AcuCarShowClient.Api.CarShowClassTypes;
using AcuCarShowClient.Api.CarShowClasses;
using AcuCarShowClient.Api.CarShowEntries;
using AcuCarShowClient.Api.CarShowFinalScores;
using AcuCarShowClient.Api.CarShowGroupCalculationMembers;
using AcuCarShowClient.Api.CarShowGroupCalculations;
using AcuCarShowClient.Api.CarShowQuestionCalculationGroupQuestions;
using AcuCarShowClient.Api.CarShowQuestionCalculationGroups;
using AcuCarShowClient.Api.CarShowScoreCalculations;
using AcuCarShowClient.Api.CarShowScoringQuestions;
using AcuCarShowClient.Api.CarShows;
using AcuCarShowClient.Api.Payments;
using AcuCarShowClient.Api.UserApplicationAccess;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AcuCarShowClient.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Applications property</summary>
        public global::AcuCarShowClient.Api.Applications.ApplicationsRequestBuilder Applications
        {
            get => new global::AcuCarShowClient.Api.Applications.ApplicationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The AppUsers property</summary>
        public global::AcuCarShowClient.Api.AppUsers.AppUsersRequestBuilder AppUsers
        {
            get => new global::AcuCarShowClient.Api.AppUsers.AppUsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarDetails property</summary>
        public global::AcuCarShowClient.Api.CarDetails.CarDetailsRequestBuilder CarDetails
        {
            get => new global::AcuCarShowClient.Api.CarDetails.CarDetailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowAnswers property</summary>
        public global::AcuCarShowClient.Api.CarShowAnswers.CarShowAnswersRequestBuilder CarShowAnswers
        {
            get => new global::AcuCarShowClient.Api.CarShowAnswers.CarShowAnswersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowClasses property</summary>
        public global::AcuCarShowClient.Api.CarShowClasses.CarShowClassesRequestBuilder CarShowClasses
        {
            get => new global::AcuCarShowClient.Api.CarShowClasses.CarShowClassesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowClassOptions property</summary>
        public global::AcuCarShowClient.Api.CarShowClassOptions.CarShowClassOptionsRequestBuilder CarShowClassOptions
        {
            get => new global::AcuCarShowClient.Api.CarShowClassOptions.CarShowClassOptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowClassTypes property</summary>
        public global::AcuCarShowClient.Api.CarShowClassTypes.CarShowClassTypesRequestBuilder CarShowClassTypes
        {
            get => new global::AcuCarShowClient.Api.CarShowClassTypes.CarShowClassTypesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowEntries property</summary>
        public global::AcuCarShowClient.Api.CarShowEntries.CarShowEntriesRequestBuilder CarShowEntries
        {
            get => new global::AcuCarShowClient.Api.CarShowEntries.CarShowEntriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowFinalScores property</summary>
        public global::AcuCarShowClient.Api.CarShowFinalScores.CarShowFinalScoresRequestBuilder CarShowFinalScores
        {
            get => new global::AcuCarShowClient.Api.CarShowFinalScores.CarShowFinalScoresRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowGroupCalculationMembers property</summary>
        public global::AcuCarShowClient.Api.CarShowGroupCalculationMembers.CarShowGroupCalculationMembersRequestBuilder CarShowGroupCalculationMembers
        {
            get => new global::AcuCarShowClient.Api.CarShowGroupCalculationMembers.CarShowGroupCalculationMembersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowGroupCalculations property</summary>
        public global::AcuCarShowClient.Api.CarShowGroupCalculations.CarShowGroupCalculationsRequestBuilder CarShowGroupCalculations
        {
            get => new global::AcuCarShowClient.Api.CarShowGroupCalculations.CarShowGroupCalculationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowQuestionCalculationGroupQuestions property</summary>
        public global::AcuCarShowClient.Api.CarShowQuestionCalculationGroupQuestions.CarShowQuestionCalculationGroupQuestionsRequestBuilder CarShowQuestionCalculationGroupQuestions
        {
            get => new global::AcuCarShowClient.Api.CarShowQuestionCalculationGroupQuestions.CarShowQuestionCalculationGroupQuestionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowQuestionCalculationGroups property</summary>
        public global::AcuCarShowClient.Api.CarShowQuestionCalculationGroups.CarShowQuestionCalculationGroupsRequestBuilder CarShowQuestionCalculationGroups
        {
            get => new global::AcuCarShowClient.Api.CarShowQuestionCalculationGroups.CarShowQuestionCalculationGroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShows property</summary>
        public global::AcuCarShowClient.Api.CarShows.CarShowsRequestBuilder CarShows
        {
            get => new global::AcuCarShowClient.Api.CarShows.CarShowsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowScoreCalculations property</summary>
        public global::AcuCarShowClient.Api.CarShowScoreCalculations.CarShowScoreCalculationsRequestBuilder CarShowScoreCalculations
        {
            get => new global::AcuCarShowClient.Api.CarShowScoreCalculations.CarShowScoreCalculationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CarShowScoringQuestions property</summary>
        public global::AcuCarShowClient.Api.CarShowScoringQuestions.CarShowScoringQuestionsRequestBuilder CarShowScoringQuestions
        {
            get => new global::AcuCarShowClient.Api.CarShowScoringQuestions.CarShowScoringQuestionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The payments property</summary>
        public global::AcuCarShowClient.Api.Payments.PaymentsRequestBuilder Payments
        {
            get => new global::AcuCarShowClient.Api.Payments.PaymentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UserApplicationAccess property</summary>
        public global::AcuCarShowClient.Api.UserApplicationAccess.UserApplicationAccessRequestBuilder UserApplicationAccess
        {
            get => new global::AcuCarShowClient.Api.UserApplicationAccess.UserApplicationAccessRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
