// <auto-generated/>
#pragma warning disable CS0618
using AcuCarShowClient.Api.CarDetails.Owner.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AcuCarShowClient.Api.CarDetails.Owner
{
    /// <summary>
    /// Builds and executes requests for operations under \api\CarDetails\owner
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OwnerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the AcuCarShowClient.api.CarDetails.owner.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AcuCarShowClient.Api.CarDetails.Owner.Item.WithOwnerItemRequestBuilder"/></returns>
        public global::AcuCarShowClient.Api.CarDetails.Owner.Item.WithOwnerItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("owner", position);
                return new global::AcuCarShowClient.Api.CarDetails.Owner.Item.WithOwnerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarDetails.Owner.OwnerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OwnerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarDetails/owner", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AcuCarShowClient.Api.CarDetails.Owner.OwnerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OwnerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/CarDetails/owner", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
